version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  ngrok:
    build:
      context: .
      dockerfile: Dockerfile.ngrok
    depends_on:
      - flask
    ports:
      - "4040:4040"